import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { useParams } from "react-router-dom";
import { api, jsonBody } from "../api";
import { AsyncState, Status } from "../components/AsyncState";
import type { Job, Page, Recommendation } from "../types";
import { taskKeys, useTaskPending } from "../taskState";

function stringList(value: unknown): string[] { return Array.isArray(value) ? value.filter((item): item is string => typeof item === "string") : []; }

export function JobDetail() {
  const { id } = useParams(); const jobId = Number(id); const client = useQueryClient(); const job = useQuery<Job>({ queryKey: ["job", jobId], queryFn: () => api(`/api/jobs/${jobId}`), enabled: Number.isFinite(jobId) }); const recs = useQuery<Page<Recommendation>>({ queryKey: ["recommendations", "job", jobId], queryFn: () => api(`/api/recommendations?job_id=${jobId}`), enabled: Number.isFinite(jobId) }); const weights = useQuery<{ total_weight: number; limit: number; suitability: "suitable" | "unsuitable" | null }>({ queryKey: ["feedback-weights", jobId], queryFn: () => api(`/api/feedback/weights?job_id=${jobId}`), enabled: Number.isFinite(jobId) }); const rec = recs.data?.items.find((item) => item.job_id === jobId);
  const qualify = useMutation({ mutationFn: () => api(`/api/jobs/${jobId}/feedback`, jsonBody({ action: "confirm_qualification" })), onSuccess: () => { void client.invalidateQueries({ queryKey: ["job", jobId] }); void client.invalidateQueries({ queryKey: ["recommendations"] }); } });
  const generateAdvice = useMutation({ mutationKey: taskKeys.tailorAdvice(jobId), mutationFn: () => api<{ updated_at: string }>(`/api/jobs/${jobId}/tailor-advice`, jsonBody({})), onSuccess: () => { void client.invalidateQueries({ queryKey: ["recommendations"] }); void client.invalidateQueries({ queryKey: ["tailor-advice-list"] }); void client.invalidateQueries({ queryKey: ["tailor-advice", jobId] }); } });
  const generateAdvicePending = useTaskPending(taskKeys.tailorAdvice(jobId));
  const feedback = useMutation({ mutationFn: ({ action, reason }: { action: string; reason?: string | null }) => api(`/api/jobs/${jobId}/feedback`, jsonBody({ action, reason })), onSuccess: () => { void client.invalidateQueries({ queryKey: ["feedback-weights", jobId] }); void client.invalidateQueries({ queryKey: ["recommendations"] }); void client.invalidateQueries({ queryKey: ["evaluation"] }); } });
  return <AsyncState loading={job.isLoading || recs.isLoading || weights.isLoading} error={(job.error ?? recs.error ?? weights.error) as Error | null}><header className="page-head job-head"><div><p className="eyebrow">岗位详情</p><h1>{job.data?.title}</h1><p>{job.data?.company}<i>·</i>{job.data?.location ?? "地点待确认"}</p></div><div className="actions"><a className="button secondary" href={job.data?.normalized_url} target="_blank" rel="noreferrer">查看原职位 ↗</a><button disabled={!rec || generateAdvicePending} onClick={() => window.confirm("确认根据该岗位生成简历修改方案？") && generateAdvice.mutate()}>{generateAdvicePending ? "生成中…" : "生成修改方案"}</button></div></header>
    <div className="job-quick-actions"><button className="text-button" onClick={() => feedback.mutate({ action: "favorite" })}>＋ 收藏岗位</button><button className="text-button" onClick={() => { const reason = window.prompt("请填写不合适原因（可留空）"); if (reason !== null) feedback.mutate({ action: "ignore", reason }); }}>− 忽略岗位</button><span>显式权重 {weights.data?.total_weight ?? 0} / ±{weights.data?.limit ?? 5}</span><button className="danger-link" onClick={() => window.confirm("重置全部显式反馈权重？") && feedback.mutate({ action: "reset_weights" })}>重置</button></div>
    <section className="panel suitability-panel"><div><p className="panel-kicker">帮推荐变得更准</p><h2>这个岗位符合你的求职目标吗？</h2><p className="muted">每次选择都会成为精度样本，不会隐式修改推荐权重。</p></div><div className="suitability-actions"><button aria-label="符合" className={weights.data?.suitability === "suitable" ? "selected" : "secondary"} onClick={() => feedback.mutate({ action: "suitable" })} disabled={feedback.isPending}>✓ 符合</button><button aria-label="不符合" className={weights.data?.suitability === "unsuitable" ? "selected negative" : "secondary"} onClick={() => { const reason = window.prompt("可选：为什么不符合？"); if (reason !== null) feedback.mutate({ action: "unsuitable", reason }); }} disabled={feedback.isPending}>× 不符合</button></div></section>
    {rec ? <><section className="score-grid"><article><span>规则</span><strong>{rec.rule_score.toFixed(1)}</strong></article><article><span>向量</span><strong>{rec.vector_score.toFixed(1)}</strong></article><article><span>LLM</span><strong>{rec.llm_score?.toFixed(1) ?? "—"}</strong></article><article><span>总分</span><strong>{rec.final_score.toFixed(1)}</strong></article></section>
    <div className="grid two"><section className="panel"><h2>硬条件</h2>{Object.entries(rec.hard_filter_details).map(([key, value]) => <div className="row-link" key={key}><span>{key}</span><span>{value ? "通过" : "不通过"}</span></div>)}{rec.qualification_pending && <div className="warning"><p>毕业年份或招聘类型待确认，不进入 Top10 和提醒。</p><button className="secondary" onClick={() => qualify.mutate()}>我已人工确认资格</button></div>}</section><section className="panel"><h2>评分元数据</h2><p><b>状态：</b><Status value={rec.rerank_status} /></p><p><b>模型：</b>{rec.model_name ?? "本地降级"}</p><p><b>提示词：</b>{rec.prompt_version}</p><p><b>评分版本：</b>{rec.scoring_version}</p></section></div>
    <section className="panel"><h2>完整证据链</h2><h3>匹配事实</h3><ul>{stringList(rec.evidence.fact_texts).map((item) => <li className="pre-wrap" key={item}>{item}</li>)}</ul>{stringList(rec.evidence.matching_facts).length > 0 && <><h3>匹配说明</h3><ul>{stringList(rec.evidence.matching_facts).map((item) => <li key={item}>{item}</li>)}</ul></>}<h3>JD 引用</h3>{stringList(rec.evidence.jd_quotes).map((item) => <blockquote key={item}>{item}</blockquote>)}<h3>能力缺口与风险</h3><ul>{[...stringList(rec.evidence.gaps), ...stringList(rec.evidence.risks)].map((item) => <li key={item}>{item}</li>)}</ul></section></> : <section className="panel"><p>该岗位尚未计算推荐证据。</p></section>}
    <section className="panel"><h2>岗位原文</h2><pre className="jd">{job.data?.description}</pre></section>{(generateAdvice.error || qualify.error || feedback.error) && <p role="alert" className="error-text">{(generateAdvice.error ?? qualify.error ?? feedback.error)?.message}</p>}{generateAdvice.data && <p className="success">修改方案已生成，可前往“06 修改建议”查看。</p>}</AsyncState>;
}
