import { useEffect, useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { api, jsonBody } from "../api";
import { AsyncState } from "../components/AsyncState";
import type { Profile as ProfileType, Resume } from "../types";

export function Profile() {
  const [editingFact, setEditingFact] = useState<string | null>(null); const [draft, setDraft] = useState("");
  const [directions, setDirections] = useState(""); const [skills, setSkills] = useState(""); const [cities, setCities] = useState(""); const [excluded, setExcluded] = useState(""); const [remote, setRemote] = useState("");
  const client = useQueryClient(); const profile = useQuery<ProfileType>({ queryKey: ["profile"], queryFn: () => api("/api/profile"), retry: false }); const resumes = useQuery<Resume[]>({ queryKey: ["resumes"], queryFn: () => api("/api/resumes") });
  useEffect(() => { if (profile.data) { setDirections(profile.data.target_directions.join("、")); setSkills(profile.data.skills.join("、")); setCities(profile.data.target_cities.join("、")); setExcluded(profile.data.exclude_keywords.join("、")); setRemote(profile.data.remote_preference ?? ""); } }, [profile.data]);
  const split = (value: string) => value.split(/[、,，\n]/).map((item) => item.trim()).filter(Boolean);
  const confirm = useMutation({ mutationFn: () => api("/api/profile/confirm", jsonBody({})), onSuccess: () => void client.invalidateQueries({ queryKey: ["profile"] }) });
  const saveProfile = useMutation({ mutationFn: () => api("/api/profile", { ...jsonBody({ target_directions: split(directions), skills: split(skills), target_cities: split(cities), exclude_keywords: split(excluded), remote_preference: remote.trim() || null }), method: "PATCH" }), onSuccess: () => void client.invalidateQueries({ queryKey: ["profile"] }) });
  const factAction = useMutation({ mutationFn: ({ id, action }: { id: string; action: string }) => api(`/api/facts/${id}`, jsonBody({ action })), onSuccess: () => void client.invalidateQueries({ queryKey: ["resumes"] }) });
  const revise = useMutation({ mutationFn: ({ id, text }: { id: string; text: string }) => api(`/api/facts/${id}`, jsonBody({ action: "revise", text })), onSuccess: () => { setEditingFact(null); setDraft(""); void client.invalidateQueries({ queryKey: ["resumes"] }); void client.invalidateQueries({ queryKey: ["profile"] }); } });
  const facts = resumes.data?.flatMap((resume) => resume.facts.filter((fact) => fact.active)) ?? [];
  return <><header className="page-head"><div><p className="eyebrow">EVIDENCE PROFILE</p><h1>画像与事实审核</h1><p>低置信度事实会标黄；确认后才允许云重排和定制简历。</p></div><button onClick={() => confirm.mutate()} disabled={!facts.length || confirm.isPending}>{profile.data?.confirmed ? "重新确认画像" : "确认画像"}</button></header>
    <AsyncState loading={profile.isLoading || resumes.isLoading} error={(profile.error ?? resumes.error) as Error | null}><section className="panel"><h2>目标画像</h2><form onSubmit={(event) => { event.preventDefault(); saveProfile.mutate(); }}><label htmlFor="directions">目标方向（用逗号或顿号分隔）</label><input id="directions" value={directions} onChange={(event) => setDirections(event.target.value)} /><label htmlFor="skills">技能</label><input id="skills" value={skills} onChange={(event) => setSkills(event.target.value)} /><label htmlFor="cities">目标城市</label><input id="cities" value={cities} onChange={(event) => setCities(event.target.value)} /><label htmlFor="remote">远程偏好</label><input id="remote" value={remote} onChange={(event) => setRemote(event.target.value)} placeholder="例如：可远程 / 仅线下" /><label htmlFor="excluded">排除关键词</label><input id="excluded" value={excluded} onChange={(event) => setExcluded(event.target.value)} /><button disabled={saveProfile.isPending}>{saveProfile.isPending ? "保存中…" : "保存画像偏好"}</button></form><p><b>版本：</b>v{profile.data?.version} · {profile.data?.confirmed ? "已确认" : "未确认"}</p><p className="muted">修改画像后需重新确认，才会参与云重排和定制简历。</p></section>
    <section className="panel"><h2>可追溯事实</h2>{facts.length ? facts.map((fact) => <article key={fact.fact_id} className={`fact ${fact.confidence < 1 ? "low" : ""}`}><div className="fact-content">{editingFact === fact.fact_id ? <div className="fact-editor"><label htmlFor={`fact-${fact.fact_id}`}>修改事实内容</label><textarea id={`fact-${fact.fact_id}`} value={draft} onChange={(event) => setDraft(event.target.value)} /><div className="actions"><button disabled={!draft.trim() || revise.isPending} onClick={() => revise.mutate({ id: fact.fact_id, text: draft })}>保存新版本</button><button className="secondary" onClick={() => setEditingFact(null)}>取消</button></div></div> : <p className="pre-wrap">{fact.redacted_text}</p>}<small>{fact.category} · {fact.page_number ? `第 ${fact.page_number} 页` : `第 ${fact.line_number ?? "?"} 行`}</small></div><div className="actions"><button className="secondary" onClick={() => factAction.mutate({ id: fact.fact_id, action: "confirm" })}>接受</button><button className="secondary" onClick={() => { setEditingFact(fact.fact_id); setDraft(fact.redacted_text); }}>修改</button><button className="danger-link" onClick={() => window.confirm("确定停用这条事实？") && factAction.mutate({ id: fact.fact_id, action: "disable" })}>停用</button></div></article>) : <p className="muted">暂无可审核事实。</p>}</section></AsyncState>{(confirm.error || saveProfile.error || factAction.error || revise.error) && <p role="alert" className="error-text">{(confirm.error ?? saveProfile.error ?? factAction.error ?? revise.error)?.message}</p>}</>;
}
