import { useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { api, jsonBody } from "../api";
import { AsyncState, Status } from "../components/AsyncState";
import type { Source } from "../types";

export function Sources() {
  const [company, setCompany] = useState(""); const [title, setTitle] = useState(""); const [url, setUrl] = useState(""); const [description, setDescription] = useState("");
  const client = useQueryClient(); const sources = useQuery<Source[]>({ queryKey: ["sources"], queryFn: () => api("/api/sources") }); const run = useMutation({ mutationFn: (keys?: string[]) => api<{ results: Array<{ source_key: string; success: boolean; error: string | null }> }>("/api/sources/run", jsonBody({ source_keys: keys, allow_browser: true, max_jobs_per_source: 100 })), onSuccess: () => void client.invalidateQueries({ queryKey: ["sources"] }) });
  const manual = useMutation({ mutationFn: () => api("/api/jobs/import", jsonBody({ company, title, url, description })), onSuccess: () => { setCompany(""); setTitle(""); setUrl(""); setDescription(""); void client.invalidateQueries({ queryKey: ["jobs"] }); } });
  return <><header className="page-head"><div><p className="eyebrow">OFFICIAL SOURCES</p><h1>来源健康</h1><p>只有 live smoke 通过的官方来源才计入 12 家验收。</p></div><button onClick={() => run.mutate(undefined)} disabled={run.isPending}>{run.isPending ? "采集中…" : "立即采集全部"}</button></header>{run.error && <p role="alert" className="error-text">{run.error.message}</p>}
  <AsyncState loading={sources.isLoading} error={sources.error} empty={!sources.data?.length}><div className="source-grid">{sources.data?.map((source) => <article className="panel source" key={source.source_key}><div><h2>{source.display_name}</h2><Status value={source.status} /></div><a href={source.official_entry} target="_blank" rel="noreferrer">官方入口</a><p>连续失败：{source.consecutive_failures}</p><p>验收：{source.stable_for_acceptance ? "计入" : "暂不计入"}</p>{source.last_error && <p className="warning">{source.last_error}</p>}<button className="secondary" onClick={() => run.mutate([source.source_key])}>单独运行</button></article>)}</div></AsyncState>
  {run.data && <section className="panel"><h2>本次结果</h2>{run.data.results.map((item) => <div className="row-link" key={item.source_key}><span>{item.source_key}</span><span>{item.success ? "成功" : item.error ?? "失败"}</span></div>)}</section>}
  <section className="panel"><h2>手工录入官方 JD</h2><p className="muted">当官方站点需要登录或采集失败时，可粘贴官方岗位链接和完整 JD；文本会按不可信输入隔离处理。</p><form onSubmit={(event) => { event.preventDefault(); manual.mutate(); }}><label htmlFor="manual-company">公司</label><input id="manual-company" required value={company} onChange={(event) => setCompany(event.target.value)} /><label htmlFor="manual-title">岗位名称</label><input id="manual-title" required value={title} onChange={(event) => setTitle(event.target.value)} /><label htmlFor="manual-url">官方岗位链接</label><input id="manual-url" type="url" required value={url} onChange={(event) => setUrl(event.target.value)} /><label htmlFor="manual-description">完整 JD（至少 20 字）</label><textarea id="manual-description" required minLength={20} value={description} onChange={(event) => setDescription(event.target.value)} /><button disabled={manual.isPending}>{manual.isPending ? "保存中…" : "保存手工岗位"}</button>{manual.isSuccess && <p className="success">岗位已保存。</p>}{manual.error && <p role="alert" className="error-text">{manual.error.message}</p>}</form></section></>;
}
